name: CI

on:
  workflow_dispatch:
    inputs:
      upload_to_release:
        description: 'Upload artifacts to GitHub release?'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

env:
  GUM_OPTIONS: '--enable-gumpp --enable-gumjs --with-devkits=gum,gumjs --disable-tests --disable-v8 --enable-frida-java-bridge'

jobs:
  android:
    strategy:
      matrix:
        id:
          - android-x86
          - android-x86_64
          - android-arm
          - android-arm64
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25
          add-to-path: false

      - name: Set ANDROID_NDK_ROOT
        run: echo "ANDROID_NDK_ROOT=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              libjson-glib-dev \
              libglib2.0-dev \
              ninja-build

      - name: Build
        run: |
          ./configure --host=${{ matrix.id }} ${{ env.GUM_OPTIONS }}
          make

      - name: Upload Gum devkit
        uses: actions/upload-artifact@v4
        with:
          name: gum-devkit-${{ matrix.id }}
          path: build/gum/devkit/

      - name: Upload GumJS devkit
        uses: actions/upload-artifact@v4
        with:
          name: gumjs-devkit-${{ matrix.id }}
          path: build/bindings/gumjs/devkit/

  release:
    if: ${{ github.event.inputs.upload_to_release == 'true' }}
    needs: android
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name || 'v1.0.0' }}
          name: Release ${{ github.ref_name || 'v1.0.0' }}
          body: 'Automated release generated by CI.'
          files: |
            gum-devkit-android-x86/**
            gum-devkit-android-x86_64/**
            gum-devkit-android-arm/**
            gum-devkit-android-arm64/**
            gumjs-devkit-android-x86/**
            gumjs-devkit-android-x86_64/**
            gumjs-devkit-android-arm/**
            gumjs-devkit-android-arm64/**
